@host = http://0.0.0.0:8080/api/v1
@phone_number = 09138038121
@user_id=1


### First request: Send OTP
POST {{host}}/send-otp
Content-Type: application/json

{
    "phone_number": "{{phone_number}}"
}

###

### Second request: Verify OTP
POST {{host}}/verify-otp
Content-Type: application/json

{
    "phone_number": "{{phone_number}}",
    "otp": "481988"
}

###

### Get User 
GET {{host}}/users/{{user_id}}


###

### Get Users
GET {{host}}/users
